### ISSUE TITLE
endplay.interact is not working for me

### ISSUE THREAD

**Issue by tameware** [dominicprice/endplay#36]
Please let me know if I'm doing this wrong! I get similar results if I invoke it as `endplay-interact`.

```
AdaM2:endplay adamw$ python3 -m endplay.interact
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/site-packages/endplay/interact/__main__.py", line 9, in <module>
    from endplay.interact.commandobject import CommandObject
  File "/usr/local/lib/python3.11/site-packages/endplay/interact/commandobject.py", line 45, in <module>
    logging.basicConfig(filename="/home/dominic/curses.txt")
  File "/usr/local/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 2050, in basicConfig
    h = FileHandler(filename, mode,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1181, in __init__
    StreamHandler.__init__(self, self._open())
                                 ^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1213, in _open
    return open_func(self.baseFilename, self.mode,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/dominic/curses.txt'

```

**Comment by dominicprice** [comment]
Hi, sorry yeah that is just a leftover hardcoded path! Fixing now, will be on pypi this evening :)

**Comment by dominicprice** [comment]
hopefully fixed in 0.5.1 https://pypi.org/project/endplay/

**Comment by tameware** [comment]
Works for me now! 

I had to obtain the new version via `git pull`. `python3 -m pip install endplay` retrieved v0.5.0b0. Is that expected?

**Comment by dominicprice** [comment]
If you didn't remove the package before, I think pip needs the `--upgrade` flag to upgrade an already installed package. Otherwise let me know what os/python version you have and I can double check against which wheels were build for the latest release :)

**Comment by tameware** [comment]
Sounds right. I’ll try and report back.
